//#pragma src
//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// USER INCLUDES
#include "main.h"
#include "i2c.h"
#include "adpcm_decoder.h"

//-----------------------------------------------------------------------------
// SMBus Interrupt Service Routine (ISR)
//-----------------------------------------------------------------------------
//
// SMBus ISR state machine
// - Master only implementation - no slave or arbitration states defined
// - All incoming data is written to global variable <SMB_DATA_IN>
// - All outgoing data is read from global variable <SMB_DATA_OUT>
// SMB0CN0::SI (SMBus Interrupt Flag)
//
SI_INTERRUPT (SMBUS0_ISR, SMBUS0_IRQn)
  {
//    SMB0CN0_SI = 0;
  /*
    bit FAIL = 0; // Used by the ISR to flag failed
    // transfers
    static bit ADDR_SEND = 0;// Used by the ISR to flag byte
    // transmissions as slave addresses
    if (SMB0CN0_ARBLOST == 0)// Check for errors
      {
        // Normal operation
        switch (SMB0CN0 & 0xF0)// Status vector
          {
            // Master Transmitter/Receiver: START condition transmitted.
            case SMB_MTSTA:
              SMB0DAT = TARGET;// Load address of the target slave
              SMB0DAT &= 0xFE;// Clear the LSB of the address for the
              // R/W bit
              SMB0DAT |= SMB_RW;// Load R/W bit
              SMB0CN0_STA = 0;// Manually clear START bit
              ADDR_SEND = 1;
              break;
            // Master Transmitter: Data byte transmitted
            case SMB_MTDB:
              if (SMB0CN0_ACK)// Slave ACK?
              {
                if (ADDR_SEND) // If the previous byte was a slave
                  { // address,
                    ADDR_SEND = 0;// Next byte is not a slave address
                    if (SMB_RW == WRITE)// If this transfer is a WRITE,
                      {
                        // send data byte
                        SMB0DAT = SMB_DATA_OUT;
                      }
                    else
                      {} // If this transfer is a READ,
                    // proceed with transfer without
                    // writing to SMB0DAT (switch
                    // to receive mode)
                  }
                else // If previous byte was not a slave
                  { // address,
                    SMB0CN0_STO = 1;// Set STO to terminate transfer
                    SMB_BUSY = 0;// And free SMBus interface
                  }
              }
            else // If slave NACK,
              {
                SMB0CN0_STO = 1; // Send STOP condition, followed
                SMB0CN0_STA = 1;// By a START
                NUM_ERRORS++;// Indicate error
              }
              break;
            // Master Receiver: byte received
            case SMB_MRDB:
              SMB_DATA_IN = SMB0DAT;// Store received byte
              SMB_BUSY = 0;// Free SMBus interface
              SMB0CN0_ACK = 0;// Send NACK to indicate last byte
              // of this transfer
              SMB0CN0_STO = 1;// Send STOP to terminate transfer
              break;
            default:
              FAIL = 1;// Indicate failed transfer
              // and handle at end of ISR
              break;
          } // end switch
      }
    else
      {
        // ARBLOST = 1, error occurred... abort transmission
        FAIL = 1;
      } // end ARBLOST if
    if (FAIL)// If the transfer failed,
      {
        SMB0CF &= ~0x80; // Reset communication
        SMB0CF |= 0x80;
        SMB0CN0_STA = 0;
        SMB0CN0_STO = 0;
        SMB0CN0_ACK = 0;
        SMB_BUSY = 0;// Free SMBus
        FAIL = 0;
        //LED = 0;
        NUM_ERRORS++;// Indicate an error occurred
      }
    SMB0CN0_SI = 0; // Clear interrupt flag
*/
  }

//-----------------------------------------------------------------------------
// TIMER3_ISR
//-----------------------------------------------------------------------------
//
// TIMER3 ISR Content goes here. Remember to clear flag bits:
// TMR3CN0::TF3H (Timer # High Byte Overflow Flag)
// TMR3CN0::TF3L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
// Timer3 Interrupt Service Routine (ISR)
//-----------------------------------------------------------------------------

//#pragma REGISTERBANK(1)
SI_INTERRUPT (TIMER3_ISR, TIMER3_IRQn)
 {
  SFRPAGE = 0x30; // page will be restored automatically at interrupt exit

  if(g_fifoSamplesPending != 0u)
  {
      DAC0L = g_pcmBuffer[g_pcmRd].u8[1]; // low byte
      DAC0H = g_pcmBuffer[g_pcmRd].u8[0]; // high byte

      g_pcmRd++;
      g_pcmRd &= 0x3FF;

      g_pcmCount--;
      g_fifoSamplesPending--;
  }
  else
  {
      DAC0L = (ADPCM_DAC_MIDPOINT & 0xFF);
      DAC0H = (ADPCM_DAC_MIDPOINT >> 8);
  }


  TMR3CN0 &= ~TMR3CN0_TF3H__BMASK; // Clear Timer3 interrupt-pending flag

  }

