//#pragma src
//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// USER INCLUDES
#include "main.h"
#include "i2c.h"
#include "adpcm_decoder.h"

//-----------------------------------------------------------------------------
// TIMER3_ISR
//-----------------------------------------------------------------------------
//
// TIMER3 ISR Content goes here. Remember to clear flag bits:
// TMR3CN0::TF3H (Timer # High Byte Overflow Flag)
// TMR3CN0::TF3L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
// Timer3 Interrupt Service Routine (ISR)
//-----------------------------------------------------------------------------

//#pragma REGISTERBANK(1)
SI_INTERRUPT (TIMER3_ISR, TIMER3_IRQn)
  {
    SFRPAGE = 0x30; // page will be restored automatically at interrupt exit

    if(g_fifoSamplesPending != 0u)
      {
        DAC0L = g_pcmBuffer[g_pcmRd].u8[1]; // low byte
        DAC0H = g_pcmBuffer[g_pcmRd].u8[0];// high byte

        g_pcmRd++;
        g_pcmRd &= 0x3FF;

        g_pcmCount--;
        g_fifoSamplesPending--;
      }
    else
      {
        DAC0L = (ADPCM_DAC_MIDPOINT & 0xFF);
        DAC0H = (ADPCM_DAC_MIDPOINT >> 8);
      }

    TMR3CN0 &= ~TMR3CN0_TF3H__BMASK; // Clear Timer3 interrupt-pending flag

  }

