//#pragma src
//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// USER INCLUDES
#include "main.h"
#include "player.h"

//-----------------------------------------------------------------------------
// TIMER3_ISR
//-----------------------------------------------------------------------------
//
// TIMER3 ISR Content goes here. Remember to clear flag bits:
// TMR3CN0::TF3H (Timer # High Byte Overflow Flag)
// TMR3CN0::TF3L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
// Timer3 Interrupt Service Routine (ISR)
//-----------------------------------------------------------------------------

//#pragma REGISTERBANK(1)
SI_INTERRUPT (TIMER3_ISR, TIMER3_IRQn)
  {
    TMR3CN0 &= ~TMR3CN0_TF3H__BMASK; // Clear Timer3 interrupt-pending flag

    SFRPAGE = 0x30;// page will be restored automatically at interrupt exit

    if(g_bufferValid)
      {
        DAC0L = g_pcmBuffer[g_pcmRd].u8[1];  // Low byte
        DAC0H = g_pcmBuffer[g_pcmRd].u8[0];// High byte
        g_pcmRd++;// Advance and wrap naturally at 256.

        // Check if we've caught up to the write pointer (buffer empty).
        if(g_pcmRd == g_pcmWr)
        g_bufferValid = 0;// Buffer is now empty.
      }
    else
      {
        // Buffer underrun: play silence.
        DAC0L = (uint8_t)(DAC_MIDPOINT & 0xFF);
        DAC0H = (uint8_t)((DAC_MIDPOINT >> 8) & 0xFF);
      }

  }

